[package]
name = "exex-primitives"
description = "Reth ExEx type-safe abstractions and implementation."
rust-version.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth.workspace = true
