[package]
name = "exex-db"
description = "Reth ExEx database utils, common types and bindings."
rust-version.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth.workspace = true
